BEGIN
	INSERT INTO Rollen	(ROL_ID, ROL_NAAM, ROL_BESCHRIJVING ) VALUES (0, 'AdminRol', 'Dit is de AdminRol');
	INSERT INTO Gebruikers (GEBRUIKER_CORPKEY, GEBRUIKER_VOORNAAM, GEBRUIKER_ACHTERNAAM, GEBRUIKER_BESCHRIJVING, GEBRUIKER_WACHTWOORD ) 	VALUES ('admin', 'The', 'Boss', 'Demo Portal Admin', 'admin123');
	INSERT INTO Director (DIRECTOR_ID, DIRECTOR_NAAM, DIRECTOR_POORT, DIRECTOR_BESCHRIJVING, DRIVER_NAAM, DRIVER_WACHTWOORD ) VALUES (0, 'director1', 8000, 'Demo Director', 'DemoDriver', 'demowachtwoord');
	INSERT INTO Clusters (CLUSTER_ID, CLUSTER_NAAM, CLUSTER_STATUS, CLUSTER_BESCHRIJVING) VALUES (0, 'cluster1', 'D', 'Demo Cluster');
	INSERT INTO Graphite (GRAPHITE_URL) VALUES ('http://graphite');
	INSERT INTO Gebruiker_Rol VALUES ('admin', 0);
	INSERT INTO Cluster_Rol VALUES (0,0);
	INSERT INTO Cluster_Director VALUES (0,0);
END